
export const orders = [
  {
    id: 'ORD015',
    item: 'Navy Blue Suit',
    image: 'https://placehold.co/64x64.png',
    dataAiHint: 'blue suit',
    type: 'Rent',
    status: 'Processing',
    date: '2025-07-15',
  },
  {
    id: 'ORD014',
    item: 'Classic White Shirt',
    image: 'https://placehold.co/64x64.png',
    dataAiHint: 'white shirt',
    type: 'Buy',
    status: 'Shipped',
    date: '2025-07-12',
  },
  {
    id: 'ORD012',
    item: 'Charcoal Gray Suit',
    image: 'https://placehold.co/64x64.png',
    dataAiHint: 'gray suit',
    type: 'Buy',
    status: 'Delivered',
    date: '2025-06-28',
  },
  {
    id: 'ORD011',
    item: 'Casual Checkered Shirt',
    image: 'https://placehold.co/64x64.png',
    dataAiHint: 'checkered shirt',
    type: 'Rent',
    status: 'Returned',
    date: '2025-06-10',
  },
  {
    id: 'ORD009',
    item: 'Classic White Shirt',
    image: 'https://placehold.co/64x64.png',
    dataAiHint: 'white shirt',
    type: 'Buy',
    status: 'Canceled',
    date: '2025-05-20',
  },
];
